### PR TITLE
previous AI was beatable

### PR DESCRIPTION
**Pull request by gj**

### CODE REVIEW

**Comment by gj** [comment]
I'm sure there's a way to refactor this to make it look prettier @pletcher, but it's definitely unbeatable

**Comment by pletcher** [comment]
@gj this looks good -- I don't want to be pedantic, but would it be possible to add a few comments? I'm thinking in particular to explain https://github.com/learn-co-curriculum/ttt-with-ai-project/pull/25/files#diff-e936986ba4f5daea11ea1f5ce757e60fR19

**Comment by gj** [comment]
Sure @pletcher –– do you mean short explanations of what each section of the AI code is checking?

**Comment by pletcher** [comment]
Yep, exactly. I just don't want students to be super bewildered :) (And it might help to spot some things that could be refactored :) )

**Comment by gj** [comment]
@pletcher -- how do those look?

**Comment by pletcher** [comment]
Awesome, thanks for doing that!

**Comment by gj** [comment]
Doesn't seem to have propagated over to the solution branch on -students

**Comment by pletcher** [comment]
Looks like it just did -- deployer woes :(

**Pull request merged**
